=== ra2003/hipergate/storage/trunk/xslt/schemas/microsite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 (http://www.xmlspy.com) by KnowGate (KnowGate) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="colors">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="color" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="container">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="guid" minOccurs="0"/>
				<xs:element ref="name"/>
				<xs:element ref="template"/>
				<xs:element ref="thumbnail"/>
				<xs:element ref="metablocks"/>
				<xs:element name="parameters" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="guid" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="containers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="container" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="family" type="xs:string"/>
	<xs:element name="fonts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="family" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="guid" type="xs:string"/>
	<xs:element name="metablock">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="template" minOccurs="0"/>
				<xs:element ref="objects" minOccurs="0"/>
				<xs:element ref="maxoccurs"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="listingOrder" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="metablocks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="metablock" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="microsite">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="fonts"/>
				<xs:element ref="colors"/>
				<xs:element ref="containers"/>
			</xs:sequence>
			<xs:attribute name="guid" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="template" type="xs:string"/>
	<xs:element name="objects" type="xs:string"/>
	<xs:element name="maxoccurs" type="xs:short"/>
	<xs:element name="thumbnail" type="xs:string"/>
</xs:schema>

=== ra2003/hipergate/storage/trunk/xslt/templates/Contemporary/Contemporary.xml
<?xml version="1.0" encoding="UTF-8"?>
<microsite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/microsite.xsd"	   
           guid="c0a80146f64790ac7c100003fcc20a22">
  <name>Contemporary</name>
  <fonts>
    <family>Arial</family>
    <family>Times</family>
    <family>Verdana</family>
  </fonts>
  <colors>
    <color>GrisOscuro-Pizarra</color>
    <color>CyanOscuro-Crimson</color>
    <color>Azul-Naranja</color>
    <color>Verde-Amarillo</color>
    <color>Burdeos-Negro</color>
  </colors>
  <containers>
    <container guid="3cd64cc2a9184d2c96b2a2fdf8f989cc">
      <name>Contemporary</name>
      <template>Contemporary.xsl</template>
      <thumbnail>Contemporary.gif</thumbnail>
      <metablocks>
        <metablock id="LOGO_SUPERIOR" listingOrder="1">
      	  <name>Logotipo Superior</name>
      	  <template>#inline:.</template>
      	  <objects>i:LOGOTIPO_CENTRAL</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="TITULAR" listingOrder="2">
      	  <name>Titular</name>
      	  <template>#inline:.</template>
      	  <objects>p:TITULAR_TEXTO,p:TITULAR_COMENTARIO,p:TITULAR_FECHA</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="BIENVENIDA" listingOrder="3">
      	  <name>Bienvenida</name>
      	  <template>#inline:.</template>
      	  <objects>p:BIENVENIDA_TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="ARTICULO" listingOrder="4">
      	  <name>Articulo</name>
      	  <template>#inline:formatArticle</template>
      	  <objects>i:IMAGEN_ARTICULO,p:TITULO_ARTICULO,p:PARRAFO_ARTICULO_[1..10],p:ENLACE_ARTICULO_[0..1]</objects>
      	  <maxoccurs>10</maxoccurs>
	</metablock>
        <metablock id="LATERAL_SUPERIOR" listingOrder="5">
      	  <name>Lateral Superior</name>
      	  <template>#inline:.</template>
      	  <objects>i:FOTO_LATERAL_SUPERIOR,p:TITULO_LATERAL_SUPERIOR,p:TEXTO_LATERAL_SUPERIOR_[1..5],p:ENLACE_LATERAL_SUPERIOR_[1..5]</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="LATERAL_CENTRAL" listingOrder="6">
      	  <name>Lateral Central</name>
      	  <template>#inline:.</template>
      	  <objects>i:FOTO_LATERAL_CENTRAL,p:TITULO_LATERAL_CENTRAL,p:TEXTO_LATERAL_CENTRAL_[1..5],p:ENLACE_LATERAL_CENTRAL_[1..5]</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="LATERAL_INFERIOR" listingOrder="7">
      	  <name>Lateral Inferior</name>
      	  <template>#inline:.</template>
      	  <objects>i:FOTO_LATERAL_INFERIOR,p:TITULO_LATERAL_INFERIOR,p:TEXTO_LATERAL_INFERIOR_[1..5],p:ENLACE_LATERAL_INFERIOR_[1..5]</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="PIE" listingOrder="8">
      	  <name>Pie de Pagina</name>
      	  <template>#inline:.</template>
      	  <objects>i:FOTO_PIE,p:PIE_EMAIL,p:PIE_CONTACTO,p:PIE_WEB,p:PIE_TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
      </metablocks>
    </container>
  </containers>
</microsite>

=== ra2003/hipergate/storage/trunk/xslt/templates/Modern/Modern.xml
<?xml version="1.0" encoding="UTF-8"?>
<microsite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/microsite.xsd"	   
           guid="c0a80146f64791f7461000068da4d550">
  <name>Modern</name>
  <fonts>
    <family>Arial</family>
    <family>Times</family>
    <family>Verdana</family>
  </fonts>
  <colors>
    <color>Azul</color>
    <color>Burdeos</color>
    <color>Dorado</color>
    <color>Naranja</color>
  </colors>
  <containers>
    <container guid="3cd64cc2a9184d2c96b2a2fdf8f989cc">
      <name>Newsletter</name>
      <template>Modern.xsl</template>
      <thumbnail>Modern.gif</thumbnail>
      <metablocks>
        <metablock id="TITULAR" listingOrder="1">
      	  <name>Titular</name>
      	  <template>#inline:.</template>
      	  <objects>p:TITULAR_TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="BIENVENIDA" listingOrder="2">
      	  <name>Bienvenida</name>
      	  <template>#inline:.</template>
      	  <objects>p:BIENVENIDA_INTRO,p:BIENVENIDA_TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="ARTICULO" listingOrder="3">
      	  <name>Articulo</name>
      	  <template>#inline:formatArticle</template>
      	  <objects>i:IMAGEN_ARTICULO,p:TITULO_ARTICULO,p:PARRAFO_ARTICULO,p:ENLACE_ARTICULO_[0..1]</objects>
      	  <maxoccurs></maxoccurs>
	</metablock>
        <metablock id="PIE" listingOrder="4">
      	  <name>Pie de Pagina</name>
      	  <template>#inline:.</template>
      	  <objects>i:FOTO_PIE,p:PIE_TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
      </metablocks>
    </container>
  </containers>
</microsite>

=== ra2003/hipergate/storage/trunk/xslt/templates/Estandar/Estandar.xml
<?xml version="1.0" encoding="UTF-8"?>
<microsite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/microsite.xsd"	   
           guid="c0a80146f5979ffc831001b2a9961864">
  <name>Estandar</name>
  <fonts>
    <family>Arial</family>
    <family>Times</family>
    <family>Verdana</family>
  </fonts>
  <colors>
    <color>rojo</color>
    <color>verde</color>
    <color>azul</color>
  </colors>
  <containers>
    <container guid="c0a80146f5bc91d683100138af53e8ab">
      <name>Home</name>
      <template>Estandar_Home.xsl</template>
      <thumbnail>Estandar.gif</thumbnail>
      <metablocks>
        <metablock id="LOGOHOME">
      	  <name>LOGOHOME</name>
      	  <template>#inline:.</template>
      	  <objects>i:LOGO-HOME,p:TEXTO-LOGO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="TEXTOHOME">
      	  <name>TEXTOHOME</name>
      	  <template>#inline:.</template>
      	  <objects>p:TEXTO-HOME</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="ENTRADA">
      	  <name>ENTRADA</name>
      	  <template>#inline:.</template>
      	  <objects>p:TITULO,p:SUBTITULO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
      </metablocks>	
    </container>
    <container guid="c0a80146f597a0327f1001b39f3f58d6">
      <name>Informacion</name>
      <template>Estandar_Informacion.xsl</template>
      <thumbnail>Estandar.gif</thumbnail>
      <metablocks>
        <metablock id="ENTRADA">
      	  <name>ENTRADA</name>
      	  <template>#inline:.</template>
      	  <objects>p:TITULO,p:SUBTITULO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="FOTOYTEXTO">
      	  <name>FOTOYTEXTO</name>
      	  <template>#inline:.</template>
      	  <objects>p:PARRAFO-TITULO,p:PARRAFO-INTRO,p:PARRAFO-ARTICULO,i:FOTO-ARTICULO</objects>
      	  <maxoccurs></maxoccurs>
	</metablock>
        <metablock id="FOTOTEXTOFOTO">
      	  <name>FOTOTEXTOFOTO</name>
      	  <template>#inline:.</template>
      	  <objects>p:PARRAFO-TITULO,p:PARRAFO-INTRO,p:PARRAFO-ARTICULO,i:FOTO-ARTICULO-IZQUIERDA,i:FOTO-ARTICULO-DERECHA</objects>
      	  <maxoccurs></maxoccurs>
	</metablock>
        <metablock id="DOCUMENTO">
      	  <name>DOCUMENTO</name>
      	  <template>#inline:.</template>
      	  <objects>p:DOCUMENTO[1..5]</objects>
      	  <maxoccurs></maxoccurs>
	</metablock>
        <metablock id="ENLACE">
      	  <name>ENLACE</name>
      	  <template>#inline:.</template>
      	  <objects>p:ENLACE[1..5]</objects>
      	  <maxoccurs></maxoccurs>
	</metablock>
      </metablocks>
    </container>
    <container guid="c0a80146f5e499cbe0100039a0156cad">
      <name>ListaCategorias</name>
      <template>Estandar_ListaCategorias.xsl</template>
      <thumbnail>Estandar.gif</thumbnail>
      <metablocks>
      </metablocks>
    </container>
    <container guid="d1b80146f5e488cbf0210040a0157bce">
      <name>ListaProductos</name>
      <template>Estandar_ListaProductos.xsl</template>
      <thumbnail>Estandar.gif</thumbnail>
      <metablocks>
      </metablocks>
      <parameters>SELECT gu_category AS category FROM k_cat_expand WHERE gu_rootcat='{#catalog}'</parameters>
    </container>
    <container guid="c0a80146f5e499cbe0100038a0156ecd">
      <name>Recursos</name>
      <template>Estandar_Recursos.xsl</template>
      <thumbnail>Estandar.gif</thumbnail>
      <metablocks>
        <metablock id="LOGOTIPO">
      	  <name>LOGOTIPO</name>
      	  <template>#inline:.</template>
      	  <objects>i:LOGOTIPO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="MENU">
      	  <name>MENU</name>
      	  <template>#inline:.</template>
      	  <objects>p:OPCION-[1..10]</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
      </metablocks>
    </container>
  </containers>
</microsite>

=== ra2003/hipergate/storage/trunk/xslt/templates/Basic/Basic.xml
<?xml version="1.0" encoding="UTF-8"?>
<microsite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/microsite.xsd" guid="0c7c148619c944819576fcec428e7350">
  <name>Basic</name>
  <fonts>
    <family>Geneva</family>
    <family>Times</family>
    <family>Verdana</family>
  </fonts>
  <colors>
    <color>Blanco-Negro</color>
  </colors>
  <containers>
    <container guid="3cd64cc2a9184d2c96b2a2fdf8f989cc">
      <name>Basic</name>
      <template>Basic.xsl</template>      
      <thumbnail>Basic.gif</thumbnail>
      <metablocks>
        <metablock id="LOGOSUPERIOR" listingOrder="1">
      	  <name>LOGO SUPERIOR</name>
      	  <template>#inline:.</template>
      	  <objects>i:LOGOKG160x36</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="CABECERA" listingOrder="2">
      	  <name>CABECERA</name>
      	  <template>#inline:.</template>
      	  <objects>p:CABECERA-TEXTO,p:CABECERA-FECHA</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="BIENVENIDA" listingOrder="3">
      	  <name>BIENVENIDA</name>
      	  <template>#inline:.</template>
      	  <objects>p:BIENVENIDA-TEXTO</objects>
      	  <maxoccurs>1</maxoccurs>
	</metablock>
        <metablock id="ARTICULO" listingOrder="4">
      	  <name>ARTICULO</name>
      	  <template>#inline:formatArticle</template>
      	  <objects>p:TITULO-SUMARIO,p:PARRAFO-SUMARIO,p:TITULO-ARTICULO,p:PARRAFO-ARTICULO-[1..10],p:ENLACE-ARTICULO-[0..1]</objects>
      	  <maxoccurs>10</maxoccurs>
	</metablock>
        <metablock id="DESTACADO" listingOrder="5">
      	  <name>DESTACADO</name>
      	  <template>#inline:.</template>
      	  <objects>p:TITULO-DESTACADO,p:TEXTO-DESTACADO-[1..10],p:ENLACE-DESTACADO-[1..10]</objects>
      	  <maxoccurs>10</maxoccurs>
	</metablock>
	<metablock id="LINKS" listingOrder="6">
      	  <name>LINKS</name>
      	  <template>#inline:.</template>
      	  <objects>p:ENLACE-LINKS-[1..10]</objects>
      	  <maxoccurs>10</maxoccurs>
	</metablock>	
      </metablocks>
    </container>
  </containers>
</microsite>
