=== ra2003/hipergate/storage/trunk/xslt/schemas/pageset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="gu_address" type="xs:string"/>
				<xs:element name="ix_address" type="xs:int"/>
				<xs:element name="gu_workarea" type="xs:string"/>
				<xs:element name="dt_created" type="xs:dateTime"/>
				<xs:element name="bo_active" type="xs:short"/>
				<xs:element name="dt_modified" type="xs:dateTime"/>
				<xs:element name="gu_user" type="xs:string"/>
				<xs:element name="tp_location" type="xs:string"/>
				<xs:element name="nm_company" type="xs:string"/>
				<xs:element name="tp_street" type="xs:string"/>
				<xs:element name="nm_street" type="xs:string"/>
				<xs:element name="nu_street" type="xs:string"/>
				<xs:element name="tx_addr1" type="xs:string"/>
				<xs:element name="tx_addr2" type="xs:string"/>
				<xs:element name="id_country" type="xs:string"/>
				<xs:element name="nm_country" type="xs:string"/>
				<xs:element name="id_state" type="xs:string"/>
				<xs:element name="nm_state" type="xs:string"/>
				<xs:element name="mn_city" type="xs:string"/>
				<xs:element name="zipcode" type="xs:string"/>
				<xs:element name="work_phone" type="xs:string"/>
				<xs:element name="direct_phone" type="xs:string"/>
				<xs:element name="home_phone" type="xs:string"/>
				<xs:element name="mov_phone" type="xs:string"/>
				<xs:element name="fax_phone" type="xs:string"/>
				<xs:element name="other_phone" type="xs:string"/>
				<xs:element name="po_box" type="xs:string"/>
				<xs:element name="tx_email" type="xs:string"/>
				<xs:element name="tx_email_alt" type="xs:string"/>
				<xs:element name="url_addr" type="xs:string"/>
				<xs:element name="coord_x" type="xs:string"/>
				<xs:element name="coord_y" type="xs:string"/>
				<xs:element name="contact_person" type="xs:string"/>
				<xs:element name="tx_salutation" type="xs:string"/>
				<xs:element name="id_ref" type="xs:string"/>
				<xs:element name="tx_remarks" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="alt" type="xs:string" nillable="true"/>
	<xs:element name="color" type="xs:string"/>
	<xs:element name="container" type="xs:string"/>
	<xs:element name="font" type="xs:string"/>
	<xs:element name="height" type="xs:unsignedLong"/>
	<xs:element name="metablock" type="xs:string"/>
	<xs:element name="microsite" type="xs:string"/>
	<xs:element name="path" type="xs:string"/>
	<xs:element name="tag" type="xs:string"/>
	<xs:element name="text" type="xs:string" nillable="true"/>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="url" type="xs:string"/>
	<xs:element name="width" type="xs:unsignedLong"/>
	<xs:element name="zone" type="xs:string" nillable="true"/>
	<xs:element name="image">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="path" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="url" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="alt" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="width" type="xs:unsignedLong" minOccurs="0" maxOccurs="1"/>
				<xs:element name="height" type="xs:unsignedLong" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="images">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="paragraph">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text" minOccurs="0"/>
				<xs:element ref="url" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="paragraphs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paragraph" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="metablock"/>
				<xs:element ref="tag"/>
				<xs:element ref="paragraphs" minOccurs="0"/>
				<xs:element ref="images" minOccurs="0"/>
				<xs:element ref="zone" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="blocks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="container"/>
				<xs:element ref="blocks"/>
			</xs:sequence>
			<xs:attribute name="guid" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pages">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="page" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pageset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="microsite"/>
				<xs:element ref="font" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="color" minOccurs="0"/>
				<xs:element ref="pages" minOccurs="0" maxOccurs="1"/>
				<xs:element name="company" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="catalog" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="addresses" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="guid" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ra2003/hipergate/storage/trunk/xslt/templates/Estandar/Estandar_Recursos.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Arial</font>
  <color>rojo</color>
  <pages>
    <page guid=":gu_pagex">
      <title><![CDATA[:page_title]]></title>
      <container>c0a80146f5e499cbe0100038a0156ecd</container>
      <blocks>
	<block id="002">
	  <metablock>MENU</metablock>
	  <tag>MENU</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="OPCION-01">
	    <text><![CDATA[Home]]></text>
	    <url>javascript:callPage("Home")</url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
          <zone/>
	</block>
	<block id="001">
	  <metablock>LOGOTIPO</metablock>
	  <tag>LOGOTIPO</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	    <image id="LOGOTIPO">
	    <path>http://images.hipergate.org/styles/Newsletter01/default_imagenarticulo.gif</path>
	    <url>javascript:callPage("Home")</url>
	    <alt>Logotipo</alt>
	    <width>100</width>
	    <height>50</height>
	    </image>
	  </images>
          <zone/>
	</block>
      </blocks>
    </page>
  </pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Estandar/Estandar_Informacion.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Arial</font>
  <color>rojo</color>
  <pages>
    <page guid=":gu_pagex">
      <title>:page_title</title>
      <container>c0a80146f597a0327f1001b39f3f58d6</container>
      <blocks>
	<block id="002">
	  <metablock>FOTOYTEXTO</metablock>
	  <tag>FOTOYTEXTO</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="PARRAFO-TITULO">
	    <text><![CDATA[<Escriba aqui el titulo de articulo>]]></text>
	    <url></url>
	    </paragraph>	  
	    <paragraph id="PARRAFO-INTRO">
	    <text><![CDATA[<Escriba aqui un parrafo introductorio>]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="PARRAFO-ARTICULO">
	    <text><![CDATA[Espacio para el texto del articulo]]></text>
	    <url></url>
	    </paragraph>
	    </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	    <image id="FOTO-ARTICULO-IZQUIERDA">
	    <path>http://images.hipergate.org/styles/estandar/defarticle.jpg</path>
	    <url></url>
	    <alt>Imagen</alt>
	    <width>96</width>
	    <height>82</height>
	    </image>
	  </images>
          <zone/>
	</block>
	<block id="001">
	  <metablock>ENTRADA</metablock>
	  <tag>ENTRADA</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="TITULO">
	    <text><![CDATA[<Titulo de la pagina>]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="SUBTITULO">
	    <text><![CDATA[<Subtitulo de la pagina>]]></text>
	    <url></url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
          <zone/>
	</block>
      </blocks>
    </page>
  </pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Traditional/Traditional.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Verdana</font>
  <color>Azul-Naranja</color>
  <pages>
    <page guid=":gu_pagex">
      <title><![CDATA[:page_title]]></title>
      <container>:gu_container</container>
      <blocks>
        <block id="001">
          <metablock>TITULAR</metablock>
          <tag>Titular</tag>
          <paragraphs>
            <paragraph id="REMOVABLE"></paragraph>
            <paragraph id="TITULAR_TEXTO">
              <text><![CDATA[Titular de la Newsletter]]></text>
              <url></url>
            </paragraph>
          </paragraphs>
          <images>
            <image id="REMOVABLE"></image>
          </images>
          <zone />
        </block>

        <block id="002">
          <metablock>BIENVENIDA</metablock>
          <tag>Bienvenida</tag>
          <paragraphs>
            <paragraph id="REMOVABLE"></paragraph>
            <paragraph id="BIENVENIDA_INTRO">
              <text><![CDATA[Estimado {#Datos.Nombre}:]]></text>
              <url></url>
            </paragraph>
            <paragraph id="BIENVENIDA_TEXTO">
              <text><![CDATA[Introduzca el texto introductorio de su newsletter. Recuerde que en este bloque puede insertar HTML directamente.]]></text>
              <url></url>
            </paragraph>
          </paragraphs>
          <images>
            <image id="REMOVABLE"></image>
          </images>
          <zone />
        </block>

        <block id="003">
          <metablock>ARTICULO</metablock>
          <tag>Articulo</tag>
          <paragraphs>
            <paragraph id="REMOVABLE"></paragraph>
            <paragraph id="TITULO_ARTICULO">
              <text><![CDATA[Titular Articulo 1]]></text>
              <url></url>
            </paragraph>
            <paragraph id="PARRAFO_ARTICULO">
              <text><![CDATA[Articulo 1]]></text>
              <url></url>
            </paragraph>
            <paragraph id="ENLACE_ARTICULO">
              <text><![CDATA[Mas Informacion]]></text>
              <url>http://www.knowgate.es/</url>
            </paragraph>
          </paragraphs>
          <images>
            <image id="REMOVABLE"></image>
            <image id="IMAGEN_ARTICULO">
              <url>http://www.knowgate.es/</url>
              <path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
              <alt><![CDATA[KnowGate.es]]></alt>
              <width><![CDATA[100]]></width>
              <height><![CDATA[100]]></height>
            </image>
          </images>
          <zone/>
        </block>

        <block id="004">
          <metablock>ARTICULO</metablock>
          <tag>Articulo</tag>
          <paragraphs>
            <paragraph id="REMOVABLE"></paragraph>
            <paragraph id="TITULO_ARTICULO">
              <text><![CDATA[Titular Articulo 2]]></text>
              <url></url>
            </paragraph>
            <paragraph id="PARRAFO_ARTICULO">
              <text><![CDATA[Articulo 2]]></text>
              <url></url>
            </paragraph>
            <paragraph id="ENLACE_ARTICULO">
              <text><![CDATA[Mas Informacion]]></text>
              <url>http://www.knowgate.es/</url>
            </paragraph>
          </paragraphs>
          <images>
            <image id="REMOVABLE"></image>
            <image id="IMAGEN_ARTICULO">
              <url>http://www.knowgate.es/</url>
              <path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
              <alt><![CDATA[KnowGate.es]]></alt>
              <width><![CDATA[100]]></width>
              <height><![CDATA[100]]></height>
            </image>
          </images>
          <zone/>
        </block>

        <block id="005">
          <metablock>PIE</metablock>
          <tag>Pie de pagina</tag>
          <paragraphs>
            <paragraph id="PIE_TEXTO">
              <text><![CDATA[Informacion Adicional (como darse de baja, CIF de la empresa, etc)]]></text>
              <url></url>
            </paragraph>
          </paragraphs>
          <images>
            <image id="REMOVABLE"></image>
            <image id="FOTO_PIE">
              <url>http://www.knowgate.es/</url>
              <path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
              <alt><![CDATA[KnowGate.es]]></alt>
              <width><![CDATA[100]]></width>
              <height><![CDATA[100]]></height>
            </image>
          </images>
          <zone/>
        </block>
      </blocks>
    </page>
  </pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Modern/Modern.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
	<microsite>:gu_microsite</microsite>
	<font>Verdana</font>
	<color>Burdeos</color>
	<pages>
		<page guid=":gu_pagex">
			<title><![CDATA[:page_title]]></title>
			<container>:gu_container</container>
			<blocks>
				<block id="001">
					<metablock>TITULAR</metablock>
					<tag>Titular</tag>
					<paragraphs>
						<paragraph id="REMOVABLE"/>
						<paragraph id="TITULAR_TEXTO">
							<text><![CDATA[Titular de la Newsletter]]></text>
							<url/>
						</paragraph>
					</paragraphs>
					<images>
						<image id="REMOVABLE"/>
					</images>
					<zone/>
				</block>
				<block id="002">
					<metablock>BIENVENIDA</metablock>
					<tag>Bienvenida</tag>
					<paragraphs>
						<paragraph id="REMOVABLE"/>
						<paragraph id="BIENVENIDA_INTRO">
							<text><![CDATA[Estimado {#Datos.Nombre}:]]></text>
							<url/>
						</paragraph>
						<paragraph id="BIENVENIDA_TEXTO">
							<text><![CDATA[Introduzca el texto introductorio de su newsletter. Recuerde que en este bloque puede insertar HTML directamente.]]></text>
							<url/>
						</paragraph>
					</paragraphs>
					<images>
						<image id="REMOVABLE"/>
					</images>
					<zone/>
				</block>
				<block id="003">
					<metablock>ARTICULO</metablock>
					<tag>Articulo</tag>
					<paragraphs>
						<paragraph id="REMOVABLE"/>
						<paragraph id="TITULO_ARTICULO">
							<text><![CDATA[Titular Articulo 1]]></text>
							<url/>
						</paragraph>
						<paragraph id="PARRAFO_ARTICULO">
							<text><![CDATA[Articulo 1]]></text>
							<url/>
						</paragraph>
						<paragraph id="ENLACE_ARTICULO">
							<text><![CDATA[Mas Informacion]]></text>
							<url>http://www.knowgate.es/</url>
						</paragraph>
					</paragraphs>
					<images>
						<image id="REMOVABLE"/>
						<image id="IMAGEN_ARTICULO">
							<path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
							<url>http://www.knowgate.es/</url>
							<alt><![CDATA[KnowGate.es]]></alt>
							<width>100</width>
							<height>100</height>
						</image>
					</images>
					<zone/>
				</block>
				<block id="004">
					<metablock>ARTICULO</metablock>
					<tag>Articulo</tag>
					<paragraphs>
						<paragraph id="REMOVABLE"/>
						<paragraph id="TITULO_ARTICULO">
							<text><![CDATA[Titular Articulo 2]]></text>
							<url/>
						</paragraph>
						<paragraph id="PARRAFO_ARTICULO">
							<text><![CDATA[Articulo 2]]></text>
							<url/>
						</paragraph>
						<paragraph id="ENLACE_ARTICULO">
							<text><![CDATA[Mas Informacion]]></text>
							<url>http://www.knowgate.es/</url>
						</paragraph>
					</paragraphs>
					<images>
						<image id="REMOVABLE"/>
						<image id="IMAGEN_ARTICULO">
							<path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
							<url>http://www.knowgate.es/</url>
							<alt><![CDATA[KnowGate.es]]></alt>
							<width>100</width>
							<height>100</height>
						</image>
					</images>
					<zone/>
				</block>
				<block id="005">
					<metablock>PIE</metablock>
					<tag>Pie de pagina</tag>
					<paragraphs>
						<paragraph id="PIE_TEXTO">
							<text><![CDATA[Informacion Adicional (como darse de baja, CIF de la empresa, etc)]]></text>
							<url/>
						</paragraph>
					</paragraphs>
					<images>
						<image id="REMOVABLE"/>
						<image id="FOTO_PIE">
							<path>http://images.hipergate.org/styles/common/default_100x100_es.gif</path>
							<url>http://www.knowgate.es/</url>
							<alt><![CDATA[KnowGate.es]]></alt>
							<width>100</width>
							<height>100</height>
						</image>
					</images>
					<zone/>
				</block>
			</blocks>
		</page>
	</pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Estandar/Estandar_Home.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Arial</font>
  <color>rojo</color>
  <pages>
    <page guid=":gu_pagex">
      <title>:page_title</title>
      <container>c0a80146f5bc91d683100138af53e8ab</container>
      <blocks>
	<block id="002">
	  <metablock>LOGOHOME</metablock>
	  <tag>LOGOHOME</tag>
          <paragraphs>
	    <paragraph id="TEXTO-LOGO">
	      <text><![CDATA[Productos y servicios variados para todos los gustos]]></text>
	      <url></url>
	    </paragraph>          
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	    <image id="LOGO-HOME">
	    <path>http://images.hipergate.org/images/logo_knowgate.gif</path>
	    <url>http://www.hipergate.org</url>
	    <alt>Imagen Home</alt>
	    <width>272</width>
	    <height>236</height>
	    </image>
	  </images>
          <zone/>
	</block>
	<block id="001">
	  <metablock>ENTRADA</metablock>
	  <tag>ENTRADA</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="TITULO">
	    <text><![CDATA[Bienvenidos a <nombre de la compania>]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="SUBTITULO">
	    <text><![CDATA[<Titulo de la pagina principal>]]></text>
	    <url></url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
          <zone/>
	</block>
      </blocks>
    </page>
    <page guid=":gu_pageres">
      <title>Recursos</title>
      <container>c0a80146f5e499cbe0100038a0156ecd</container>
      <blocks>
	<block id="002">
	  <metablock>MENU</metablock>
	  <tag>MENU</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="OPCION-01">
	    <text><![CDATA[Home]]></text>
	    <url>javascript:callPage("Home")</url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
          <zone/>
	</block>
	<block id="001">
	  <metablock>LOGOTIPO</metablock>
	  <tag>LOGOTIPO</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	    <image id="LOGOTIPO">
	    <path>http://images.hipergate.org/styles/estandar/defarticle.jpg</path>
	    <url>javascript:callPage("Home")</url>
	    <alt>Logotipo</alt>
	    <width>96</width>
	    <height>82</height>
	    </image>
	  </images>
          <zone/>
	</block>
      </blocks>
    </page>
  </pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Estandar/Estandar_ListaProductos.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Arial</font>
  <color>rojo</color>
  <pages>
    <page guid=":gu_pagex">
      <title>:page_title</title>
      <container>d1b80146f5e488cbf0210040a0157bce</container>
      <blocks>
      </blocks>
    </page>
  </pages>
</pageset>

=== ra2003/hipergate/storage/trunk/xslt/templates/Basic/Basic.datatemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<pageset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.hipergate.org/xslt/schemas/pageset.xsd" guid=":gu_pageset">
  <microsite>:gu_microsite</microsite>
  <font>Verdana</font>
  <color>Blanco-Negro</color>
  <pages>
    <page guid=":gu_pagex">
      <title><![CDATA[:page_title]]></title>
      <container>:gu_container</container>
      <blocks>
	<block id="004">
	  <metablock>DESTACADO</metablock>
	  <tag>DESTACADO</tag>
	  <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="TITULO-DESTACADO">
	    <text><![CDATA[Título de destacados]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="TEXTO-DESTACADO-01">
	    <text><![CDATA[Texto destacado 1]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="TEXTO-DESTACADO-02">
	    <text><![CDATA[Texto destacado 2]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="TEXTO-DESTACADO-03">
	    <text><![CDATA[Texto destacado 3]]></text>
	    <url></url>
	    </paragraph>
   	    <paragraph id="ENLACE-DESTACADO-01">
	    <text><![CDATA[Enlace destacado 1]]></text>
	    <url>www.hipergate.es</url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
	  <zone/>
	</block>
	<block id="003">
	  <metablock>LOGOSUPERIOR</metablock>
	  <tag>LOGOSUPERIOR</tag>
	  <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	    <image id="LOGOKG160x36">
	      <path>http://www.hipergate.org/images/topLogo.gif</path>
	      <url>www.hipergate.org</url>
	      <alt><![CDATA[LOGOSUPERIOR]]></alt>
	      <width>200</width>
	      <height>50</height>
	    </image>
	  </images>
	  <zone/>
	</block>
	<block id="002">
	  <metablock>ARTICULO</metablock>
	  <tag>ARTICULO</tag>
	  <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="TITULO-ARTICULO">
	    <text><![CDATA[Título de artículo 1]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="PARRAFO-ARTICULO-03">
	    <text><![CDATA[Párrafo 3 de artículo 1]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="PARRAFO-ARTICULO-02">
	    <text><![CDATA[Párrafo 2 de artículo 1]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="PARRAFO-ARTICULO-01">
	    <text><![CDATA[Párrafo 1 de artículo 1]]></text>
	    <url></url>
	    </paragraph>
	  </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
	  <zone/>
	</block>
	<block id="001">
	  <metablock>CABECERA</metablock>
	  <tag>CABECERA</tag>
          <paragraphs>
	    <paragraph id="REMOVABLE"></paragraph>
	    <paragraph id="CABECERA-TEXTO">
	    <text><![CDATA[Aqui puede insertar un texto de cabecera...]]></text>
	    <url></url>
	    </paragraph>
	    <paragraph id="CABECERA-FECHA">
	    <text><![CDATA[{#Sistema.Fecha}]]></text>
	    <url></url>
	    </paragraph>
          </paragraphs>
	  <images>
	    <image id="REMOVABLE"></image>
	  </images>
          <zone/>
	</block>
      </blocks>
    </page>
  </pages>
</pageset>
